/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cabs;

import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author viraj
 */
public class DriverDetails extends javax.swing.JFrame {
    String userid;
    String arr[];
    String driverid;
    String d;
    int min_distance;
    int duration;
    int count = 0;
    Connection connect=null;
    
    /**
     * Creates new form DriverDetails
     */
    public DriverDetails(String user, String ar[], String d_main, int min_d, int travel, String drop) {
        initComponents();
        connect = userdb.dbconnect();
        
        userid = user;
        arr = ar;
        driverid = d_main;
        d = drop;
        min_distance = min_d;
        duration = travel;
        //System.out.println("user "+ user);
        //System.out.println("arr "+ arr[3]);
        //System.out.println("d_main   "+ d_main);
      
        this.setVisible(true);
       this.setLocationRelativeTo(null);
       String sql="Select * from driver where dusername=?";
            try{
              
                PreparedStatement pst1=connect.prepareStatement(sql);
                pst1.setString(1, driverid);
                
                ResultSet rs=pst1.executeQuery();
                driverName.setText(rs.getString("dname"));
                
             
                driverPhone.setText(rs.getString("dphone"));
                
                
                driverCar.setText(rs.getString("dcar"));
                
                
                driverCarNo.setText(rs.getString("dcarno"));
                
                
                driverRating.setText(rs.getString("drating"));
                
                
                tripDuration.setText(String.valueOf(duration * 10) + " minutes." );
                
                
                fare.setText(String.valueOf(duration * 10) + " INR." );
                
                
                driverETA.setText(String.valueOf(min_distance * 10) + " minutes." );
                pst1.close();
            }
                
                catch (SQLException ex) {
            System.out.println(ex.getMessage());
                }
        
    }
    
    
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dphonenumber = new javax.swing.JLabel();
        driverName = new javax.swing.JLabel();
        driverPhone = new javax.swing.JLabel();
        driverCar = new javax.swing.JLabel();
        driverCarNo = new javax.swing.JLabel();
        driverRating = new javax.swing.JLabel();
        tripDuration = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        fare = new javax.swing.JLabel();
        driverETA = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Driver Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 51, 110, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Driver's Phone Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 96, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Car License Plate Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 183, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Car Build");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Driver Rating");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 225, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Trip Duration");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 271, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Estimated Fare");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 317, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Driver will be at your location in");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 358, -1, -1));
        getContentPane().add(dphonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 96, -1, -1));

        driverName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        driverName.setText("...");
        getContentPane().add(driverName, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 51, 130, -1));

        driverPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        driverPhone.setText("...");
        getContentPane().add(driverPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 96, 120, -1));

        driverCar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        driverCar.setText("...");
        getContentPane().add(driverCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 140, 160, -1));

        driverCarNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        driverCarNo.setText("...");
        getContentPane().add(driverCarNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 183, 140, -1));

        driverRating.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        driverRating.setText("...");
        getContentPane().add(driverRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 225, 81, -1));

        tripDuration.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tripDuration.setText("...");
        getContentPane().add(tripDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 271, 140, -1));

        confirm.setBackground(new java.awt.Color(0, 0, 153));
        confirm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        confirm.setForeground(new java.awt.Color(255, 255, 255));
        confirm.setText("Confirm Booking");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        getContentPane().add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 402, -1, -1));

        cancel.setBackground(new java.awt.Color(0, 0, 153));
        cancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel Booking");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 402, -1, -1));

        fare.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fare.setText("...");
        getContentPane().add(fare, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 317, 110, -1));

        driverETA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        driverETA.setText("...");
        getContentPane().add(driverETA, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 358, 130, -1));

        jLabel9.setFont(new java.awt.Font("Calibri Light", 3, 22)); // NOI18N
        jLabel9.setText("Driver's Details");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 153, 0));
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new RequestCab(userid, driverid, min_distance, duration).setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
        
        try{
            String sql="UPDATE user SET status=? WHERE username=?";
            PreparedStatement pst1= connect.prepareStatement(sql);
            pst1.setString(1, String.valueOf(1));
            pst1.setString(2, userid);
            pst1.executeUpdate();
            pst1.close();
            sql="UPDATE driver SET dstatus=? WHERE dusername=?";
            pst1= connect.prepareStatement(sql);
            pst1.setString(1, String.valueOf(1));
            pst1.setString(2, driverid);
            pst1.executeUpdate();
            pst1.close();

        }
        
        catch (SQLException ex) {
            System.out.println(ex.getMessage());
                }
        
        JOptionPane.showMessageDialog(null,"Your booking was successful!");
                new java.util.Timer().schedule(new java.util.TimerTask()
                {
                    @Override
                    public void run()
                    {
                        System.out.println("timer created");
                        new thanks(userid, driverid, duration, d).setVisible(true);
                        
                        //driverWindow = new Driver(driver,temp,ans);
                //driverWindow.setVisible(true);
                       //putd = RequestCabs()
                       //.setVisible(false);
                        //new rating(pickup,drop,temp,driver).setVisible(true);
                    }

                    private void setVisible(boolean b) {
                        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                    }
                }, 10000);
        
        this.setVisible(false);
        new RequestCab(userid, driverid, min_distance, duration).setVisible(true);
    }//GEN-LAST:event_confirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public void arr() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DriverDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DriverDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DriverDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DriverDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DriverDetails(userid, arr, driverid, min_distance, duration, d).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton confirm;
    private javax.swing.JLabel dphonenumber;
    private javax.swing.JLabel driverCar;
    private javax.swing.JLabel driverCarNo;
    private javax.swing.JLabel driverETA;
    private javax.swing.JLabel driverName;
    private javax.swing.JLabel driverPhone;
    private javax.swing.JLabel driverRating;
    private javax.swing.JLabel fare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel tripDuration;
    // End of variables declaration//GEN-END:variables
}
