/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cabs;

import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author viraj
 */
public class RequestCab extends javax.swing.JFrame {
Connection connect=null;
    boolean flag = true;
    String userid;
    String str = "";
    String driverid;
    int min_distance = 0;
    int duration = 0;
    int count = 0;
    int balance;
    /**
     * Creates new form RequestCab
     */
    public RequestCab(String user, String driver_id, int min_dist, int travel) {
        initComponents();
        
        connect = userdb.dbconnect();
        userid = user;
        driverid = driver_id;
        min_distance = min_dist;
        duration = travel;
        this.setLocationRelativeTo(null);
        
        try{
            String query1="SELECT name FROM user WHERE username=? ";
            PreparedStatement pst1=connect.prepareStatement(query1);
            pst1.setString(1, userid);
            ResultSet rs1=pst1.executeQuery();
            customer_name.setText(rs1.getString("name"));
            pst1.close();
            rs1.close();
            
            
    }
        catch (SQLException ex) {
            System.out.println(ex.getMessage());}}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        request = new javax.swing.JButton();
        addmoney = new javax.swing.JButton();
        status = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        customer_name = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        view = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setBackground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("jLabel3");
        jLabel3.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        request.setBackground(new java.awt.Color(0, 0, 153));
        request.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        request.setForeground(new java.awt.Color(255, 255, 255));
        request.setText("Request a cab");
        request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestActionPerformed(evt);
            }
        });
        getContentPane().add(request, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 260, -1));

        addmoney.setBackground(new java.awt.Color(0, 0, 153));
        addmoney.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        addmoney.setForeground(new java.awt.Color(255, 255, 255));
        addmoney.setText("Add money to wallet");
        addmoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmoneyActionPerformed(evt);
            }
        });
        getContentPane().add(addmoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 260, -1));

        status.setBackground(new java.awt.Color(0, 0, 153));
        status.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setText("View Current Ride Status");
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 260, -1));

        jLabel1.setFont(new java.awt.Font("Calibri Light", 3, 18)); // NOI18N
        jLabel1.setText("Welcome ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 80, 35));

        customer_name.setFont(new java.awt.Font("Calibri Light", 3, 18)); // NOI18N
        customer_name.setText(".....");
        getContentPane().add(customer_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 130, 35));

        logout.setBackground(new java.awt.Color(0, 0, 153));
        logout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabs/timeless-treasures-new-york-city-taxi-cabs-black-fabric-Lg.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 440));

        view.setBackground(new java.awt.Color(0, 51, 153));
        view.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        view.setForeground(new java.awt.Color(255, 255, 255));
        view.setText("View balance");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        getContentPane().add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 260, -1));

        jLabel4.setBackground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("jLabel4");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 590, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void requestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestActionPerformed
        // TODO add your handling code here:
        
        
        
        
        String sql="Select * from driver";
            try{
              
                PreparedStatement pst= connect.prepareStatement(sql);
                
                ResultSet rs=pst.executeQuery();
                while(rs.next())
                {
                    count = count + Integer.valueOf(rs.getString("dstatus"));
                }
                pst.close();
                rs.close();
                
               String s = "Select status from user where username=?";
               PreparedStatement p= connect.prepareStatement(s);
               p.setString(1, userid);
               ResultSet r=p.executeQuery();
               int x = Integer.valueOf(r.getString("status"));
               if(x==1)
               {
                   flag =  false;
                   JOptionPane.showMessageDialog(null,"You are already in a trip. Click on View Current Ride Status for details.");
               }
               p.close();
               r.close();
               
                
                String query2="SELECT wallet FROM user WHERE username=? ";
            PreparedStatement pst2=connect.prepareStatement(query2);
            pst2.setString(1, userid);
            ResultSet rs2=pst2.executeQuery();
            str = rs2.getString("wallet");
            balance = Integer.valueOf(str);
            System.out.println(balance);
            if(balance < 300)
            {
                flag = false;
                JOptionPane.showMessageDialog(null,"Your balance is less than 300 INR.");
            }
            pst2.close();
            rs2.close();
            
            }
      
            
            catch (SQLException ex) {
            System.out.println(ex.getMessage());
                }
            
            if(count == 10)
            {
                flag = false;
                JOptionPane.showMessageDialog(null,"No cabs available right now.");
            }
           
            
        if(flag)
        {
        this.setVisible(false);
        new CabBooking(userid).setVisible(true);}
     
    }//GEN-LAST:event_requestActionPerformed

    private void addmoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmoneyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AddMoney(userid).setVisible(true);
    }//GEN-LAST:event_addmoneyActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
       boolean check = true;     
        try{
                String sql="Select status from user";
                PreparedStatement pst= connect.prepareStatement(sql);
                
                ResultSet rs=pst.executeQuery();
                String s = rs.getString("status");
                int i = Integer.valueOf(s);
                if(i == 0)
                    check = false;
                else if(i == 1)
                    check = true;
                pst.close();
                rs.close();
            
            }
      
            
            catch (SQLException ex) {
            System.out.println(ex.getMessage());
                }
           if(check){
               this.setVisible(false);
        new WaitingWindow(userid, driverid, min_distance, duration).setVisible(true);
           }
           else{
              JOptionPane.showMessageDialog(null,"You have not booked a cab."); 
           }
// TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
      this.setVisible(false);
        new main().setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
        String s ="";
        try{
             String sql="Select wallet from user where username = ?";
                PreparedStatement pst= connect.prepareStatement(sql);
                pst.setString(1, userid);
                ResultSet rs=pst.executeQuery();
                s = rs.getString("wallet");
                pst.close();
                rs.close();
        }
        catch (SQLException ex) {
            System.out.println(ex.getMessage());
                }
        JOptionPane.showMessageDialog(null,"Your current balance in wallet is " + s);
    }//GEN-LAST:event_viewActionPerformed

    /**
     * @param args the command line arguments
     */
    public void arr(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequestCab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequestCab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequestCab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequestCab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequestCab(userid, driverid, min_distance, duration).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addmoney;
    private javax.swing.JLabel customer_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton logout;
    private javax.swing.JButton request;
    private javax.swing.JButton status;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
