/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cabs;

import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.lang.*;
import java.util.Random;
/**
 *
 * @author viraj
 */
public class thanks extends javax.swing.JFrame {
    Connection connect=null;
    String userid;
    String driverid;
    String d;
    int fare = 0, balance = 0;
   // int rating;
    String[] arr = new String[]{"Select","Panipat","Pilibhit","Faridabad","Ajmer","Jodhpur","Hyderabad","Bangalore","Delhi","Jammu","SriGanganagar","Khandwa","Mumbai","Jaipur","Saharanpur","Vadodara","Kanpur","Jharsuguda","Chandigarh","Ludhiana","Rohtak"};
    //String p = arr[pickUp.getSelectedIndex()];
    
    /**
     * Creates new form thanks
     */
    public thanks(String user_id, String driver_id, int travel, String drop) {
         
        connect = userdb.dbconnect();
        userid = user_id;
        driverid = driver_id;
        fare = travel * 10;
        d = drop;
        this.setLocationRelativeTo(null);
       initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("Thank you for Riding with us!!!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 500, 51));

        ok.setBackground(new java.awt.Color(204, 0, 204));
        ok.setForeground(new java.awt.Color(255, 255, 255));
        ok.setText("Ok");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 80, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setText("Rate your trip :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 110, 60));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabs/thanksflower.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
                
            try{
            String query3="UPDATE user SET status=? WHERE username=?";
            PreparedStatement pst3=connect.prepareStatement(query3);
            pst3.setString(1, String.valueOf(0));
            pst3.setString(2, userid);
            pst3.executeUpdate();
            pst3.close();
            //System.out.println("three");
            String query4="UPDATE driver SET dstatus=? WHERE dusername=?";
            PreparedStatement pst4=connect.prepareStatement(query4);
            pst4.setString(1, String.valueOf(0));
            pst4.setString(2, driverid);
            pst4.executeUpdate();
            pst4.close();
            //System.out.println("four");
            String query1="SELECT wallet FROM user WHERE username=? ";
            PreparedStatement pst1=connect.prepareStatement(query1);
            pst1.setString(1, userid);
            ResultSet rs=pst1.executeQuery();
            String x = rs.getString("wallet");
            //Double d = Double.valueOf(x);
            
            //System.out.println("Wallet : "+ Integer.valueOf(rs.getString("wallet")));
            pst1.close();
            rs.close();
            balance = Integer.valueOf(x);
            //System.out.println("one");
            String query2="UPDATE user SET wallet=? WHERE username=?";
            PreparedStatement pst2=connect.prepareStatement(query2);
            pst2.setString(2, userid);
            int total = balance - fare;
            pst2.setString(1, String.valueOf(total));
            pst2.executeUpdate();
            //System.out.println("two");
            pst2.close();
            int t= 1;
           {
            String query6="SELECT * FROM driver ";
            PreparedStatement pst6=connect.prepareStatement(query6);
            ResultSet rs1=pst6.executeQuery();
            while(rs1.next()){
               // t=1;
                if(rs1.getString("dstatus").equals(String.valueOf(0))){
                   String us = rs1.getString("dusername");
                    t=1;
                    //System.out.println("entered of t :"+t);
                    Random random = new Random();
                    int rand = 0;
                    while(t<21)
                    {
                    rand =0;
                    while (true){
                        rand = random.nextInt(21);
                        if(rand !=0) break;
                        }
                   // System.out.println("value of rand is :"+rand);
                    t++;
                }
                    String query7="UPDATE driver SET dlocation=? WHERE dusername=?";
                    PreparedStatement pst7=connect.prepareStatement(query7);
                    pst7.setString(1,arr[rand]);
                    pst7.setString(2, us);
                    pst7.executeUpdate();
                    pst7.close();
                    }
                }
            pst6.close();
            rs1.close();
           }
            /*Random random = new Random();
            int rand = 0;
            while (true){
                rand = random.nextInt(21);
                if(rand !=0) break;
                }
            System.out.println( "rando is "+rand);
            String set = arr[rand];
            String query5="UPDATE driver SET dlocation=? WHERE dusername=?";
            PreparedStatement pst5=connect.prepareStatement(query5);
            pst5.setString(1, set);
            pst5.setString(2, driverid);
            pst5.executeUpdate();
            pst5.close();*/
            
           // rating = Integer.valueOf(rate.getText());
            
            //rs.close();
            //pst1.close();
            //pst2.close();
            this.setVisible(false);}
            
            catch (SQLException ex) {
            System.out.println(ex.getMessage());}
    }//GEN-LAST:event_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public void arf() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(thanks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(thanks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(thanks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(thanks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new thanks().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables

}